services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: productapi-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Your_password123"
    ports:
      - "1433:1433"

  api:
    build:
      context: .
      dockerfile: src/ProductApi.Api/Dockerfile
    container_name: productapi-api
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=ProductApi;User Id=sa;Password=Your_password123;TrustServerCertificate=True"
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver